export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_NOTES = 'UPDATE_NOTES';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const UPDATE_BOARDS = 'UPDATE_BOARDS';
export const ADD_NEW_BOARD = 'ADD_NEW_BOARD';
export const UPDATE_TASKLISTS = 'UPDATE_TASKLISTS';
export const UPDATE_ENTITY_VISIBLE = 'UPDATE_ENTITY_VISIBLE';

export const ENTITY_VISIBLE_ID_NOTES = 'notes';
export const ENTITY_VISIBLE_ID_BOARDS = 'boards';
export const ENTITY_VISIBLE_ID_TASKLISTS = 'tasklists';

export const SET_USER_ACTION = 'SET_USER_ACTION';
export const ACTION_NONE = 'NONE';
export const ACTION_CREATE_BOARD = 'ACTION_CREATE_BOARD';
